In [2]:
import tensorflow as tf
import numpy as np

xy = np.loadtxt('../data-01-test-score.csv', delimiter = ',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

#make sure the shape and data are ok
print(x_data, "\nx_data shape:", x_data.shape)
print(y_data, "\ny_data shape:", y_data.shape)

tf.model = tf.keras.Sequential()
# activation function doesn't have to be added as a separate layer. Add it as an argument of Dense() layer
tf.model.add(tf.keras.layers.Dense(units=1, input_dim=3, activation='linear'))
# tf.model.add(tf.keras.layers.Activation('linear'))
tf.model.summary()

tf.model.compile(loss='mse', optimizer=tf.keras.optimizers.SGD(lr=1e-5))
history = tf.model.fit(x_data, y_data, epochs=2000)

#ask my score
print("Your score will be ", tf.model.predict([[100,70,101]]))
print("Other scores will be ", tf.model.predict([[60,70,110], [90,100,80]]))


[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 
x_data shape: (25, 3)
[[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]] 
y_data shape: (25, 1)
Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 1)                 4         
Total params: 4
Trainable params: 4
Non-trainable params: 0
______________________

1/1 [==============================] - 0s 2ms/step - loss: 15.7815
Epoch 88/2000
1/1 [==============================] - 0s 2ms/step - loss: 15.7764
Epoch 89/2000
1/1 [==============================] - 0s 2ms/step - loss: 15.7714
Epoch 90/2000
1/1 [==============================] - 0s 2ms/step - loss: 15.7664
Epoch 91/2000
1/1 [==============================] - 0s 2ms/step - loss: 15.7613
Epoch 92/2000
1/1 [==============================] - 0s 2ms/step - loss: 15.7563
Epoch 93/2000
1/1 [==============================] - 0s 5ms/step - loss: 15.7513
Epoch 94/2000
1/1 [==============================] - 0s 997us/step - loss: 15.7462
Epoch 95/2000
1/1 [==============================] - 0s 996us/step - loss: 15.7412
Epoch 96/2000
1/1 [==============================] - 0s 997us/step - loss: 15.7362
Epoch 97/2000
1/1 [==============================] - 0s 2ms/step - loss: 15.7312
Epoch 98/2000
1/1 [==============================] - 0s 2ms/step - loss: 15.7262
Epoch 99/2000
1/1 [=================

1/1 [==============================] - 0s 3ms/step - loss: 15.2954
Epoch 187/2000
1/1 [==============================] - 0s 4ms/step - loss: 15.2907
Epoch 188/2000
1/1 [==============================] - 0s 2ms/step - loss: 15.2859
Epoch 189/2000
1/1 [==============================] - 0s 5ms/step - loss: 15.2811
Epoch 190/2000
1/1 [==============================] - 0s 998us/step - loss: 15.2763
Epoch 191/2000
1/1 [==============================] - 0s 5ms/step - loss: 15.2716
Epoch 192/2000
1/1 [==============================] - 0s 2ms/step - loss: 15.2668
Epoch 193/2000
1/1 [==============================] - 0s 2ms/step - loss: 15.2620
Epoch 194/2000
1/1 [==============================] - 0s 2ms/step - loss: 15.2573
Epoch 195/2000
1/1 [==============================] - 0s 3ms/step - loss: 15.2525
Epoch 196/2000
1/1 [==============================] - 0s 2ms/step - loss: 15.2478
Epoch 197/2000
1/1 [==============================] - 0s 2ms/step - loss: 15.2430
Epoch 198/2000
1/1 [=========

1/1 [==============================] - 0s 992us/step - loss: 14.8345
Epoch 286/2000
1/1 [==============================] - 0s 997us/step - loss: 14.8299
Epoch 287/2000
1/1 [==============================] - 0s 2ms/step - loss: 14.8254
Epoch 288/2000
1/1 [==============================] - 0s 998us/step - loss: 14.8209
Epoch 289/2000
1/1 [==============================] - 0s 999us/step - loss: 14.8164
Epoch 290/2000
1/1 [==============================] - 0s 2ms/step - loss: 14.8118
Epoch 291/2000
1/1 [==============================] - 0s 2ms/step - loss: 14.8073
Epoch 292/2000
1/1 [==============================] - 0s 998us/step - loss: 14.8028
Epoch 293/2000
1/1 [==============================] - 0s 2ms/step - loss: 14.7983
Epoch 294/2000
1/1 [==============================] - 0s 997us/step - loss: 14.7938
Epoch 295/2000
1/1 [==============================] - 0s 2ms/step - loss: 14.7893
Epoch 296/2000
1/1 [==============================] - 0s 2ms/step - loss: 14.7848
Epoch 297/2000
1/1 

1/1 [==============================] - 0s 2ms/step - loss: 14.3972
Epoch 385/2000
1/1 [==============================] - 0s 4ms/step - loss: 14.3929
Epoch 386/2000
1/1 [==============================] - 0s 2ms/step - loss: 14.3886
Epoch 387/2000
1/1 [==============================] - 0s 2ms/step - loss: 14.3843
Epoch 388/2000
1/1 [==============================] - 0s 2ms/step - loss: 14.3800
Epoch 389/2000
1/1 [==============================] - 0s 4ms/step - loss: 14.3757
Epoch 390/2000
1/1 [==============================] - 0s 998us/step - loss: 14.3714
Epoch 391/2000
1/1 [==============================] - 0s 4ms/step - loss: 14.3671
Epoch 392/2000
1/1 [==============================] - 0s 998us/step - loss: 14.3629
Epoch 393/2000
1/1 [==============================] - 0s 989us/step - loss: 14.3586
Epoch 394/2000
1/1 [==============================] - 0s 998us/step - loss: 14.3543
Epoch 395/2000
1/1 [==============================] - 0s 4ms/step - loss: 14.3500
Epoch 396/2000
1/1 [===

1/1 [==============================] - 0s 998us/step - loss: 13.9824
Epoch 484/2000
1/1 [==============================] - ETA: 0s - loss: 13.97 - 0s 3ms/step - loss: 13.9783
Epoch 485/2000
1/1 [==============================] - 0s 2ms/step - loss: 13.9742
Epoch 486/2000
1/1 [==============================] - 0s 3ms/step - loss: 13.9701
Epoch 487/2000
1/1 [==============================] - 0s 999us/step - loss: 13.9661
Epoch 488/2000
1/1 [==============================] - 0s 989us/step - loss: 13.9620
Epoch 489/2000
1/1 [==============================] - 0s 997us/step - loss: 13.9579
Epoch 490/2000
1/1 [==============================] - 0s 2ms/step - loss: 13.9539
Epoch 491/2000
1/1 [==============================] - 0s 2ms/step - loss: 13.9498
Epoch 492/2000
1/1 [==============================] - 0s 4ms/step - loss: 13.9457
Epoch 493/2000
1/1 [==============================] - 0s 998us/step - loss: 13.9417
Epoch 494/2000
1/1 [==============================] - 0s 2ms/step - loss: 13.93

1/1 [==============================] - 0s 2ms/step - loss: 13.5888
Epoch 583/2000
1/1 [==============================] - 0s 2ms/step - loss: 13.5849
Epoch 584/2000
1/1 [==============================] - 0s 5ms/step - loss: 13.5810
Epoch 585/2000
1/1 [==============================] - 0s 2ms/step - loss: 13.5772
Epoch 586/2000
1/1 [==============================] - 0s 5ms/step - loss: 13.5733
Epoch 587/2000
1/1 [==============================] - 0s 2ms/step - loss: 13.5694
Epoch 588/2000
1/1 [==============================] - 0s 2ms/step - loss: 13.5656
Epoch 589/2000
1/1 [==============================] - 0s 3ms/step - loss: 13.5617
Epoch 590/2000
1/1 [==============================] - 0s 2ms/step - loss: 13.5579
Epoch 591/2000
1/1 [==============================] - 0s 2ms/step - loss: 13.5540
Epoch 592/2000
1/1 [==============================] - 0s 3ms/step - loss: 13.5502
Epoch 593/2000
1/1 [==============================] - 0s 2ms/step - loss: 13.5463
Epoch 594/2000
1/1 [===========

1/1 [==============================] - 0s 2ms/step - loss: 13.2153
Epoch 682/2000
1/1 [==============================] - 0s 2ms/step - loss: 13.2116
Epoch 683/2000
1/1 [==============================] - 0s 2ms/step - loss: 13.2079
Epoch 684/2000
1/1 [==============================] - 0s 2ms/step - loss: 13.2043
Epoch 685/2000
1/1 [==============================] - 0s 2ms/step - loss: 13.2006
Epoch 686/2000
1/1 [==============================] - 0s 993us/step - loss: 13.1969
Epoch 687/2000
1/1 [==============================] - 0s 1ms/step - loss: 13.1933
Epoch 688/2000
1/1 [==============================] - 0s 3ms/step - loss: 13.1896
Epoch 689/2000
1/1 [==============================] - 0s 2ms/step - loss: 13.1859
Epoch 690/2000
1/1 [==============================] - 0s 2ms/step - loss: 13.1823
Epoch 691/2000
1/1 [==============================] - 0s 2ms/step - loss: 13.1786
Epoch 692/2000
1/1 [==============================] - 0s 2ms/step - loss: 13.1750
Epoch 693/2000
1/1 [=========

1/1 [==============================] - 0s 2ms/step - loss: 12.8609
Epoch 781/2000
1/1 [==============================] - 0s 999us/step - loss: 12.8574
Epoch 782/2000
1/1 [==============================] - 0s 2ms/step - loss: 12.8539
Epoch 783/2000
1/1 [==============================] - 0s 2ms/step - loss: 12.8504
Epoch 784/2000
1/1 [==============================] - 0s 2ms/step - loss: 12.8469
Epoch 785/2000
1/1 [==============================] - 0s 3ms/step - loss: 12.8434
Epoch 786/2000
1/1 [==============================] - 0s 2ms/step - loss: 12.8399
Epoch 787/2000
1/1 [==============================] - 0s 3ms/step - loss: 12.8365
Epoch 788/2000
1/1 [==============================] - 0s 2ms/step - loss: 12.8330
Epoch 789/2000
1/1 [==============================] - 0s 998us/step - loss: 12.8295
Epoch 790/2000
1/1 [==============================] - 0s 3ms/step - loss: 12.8261
Epoch 791/2000
1/1 [==============================] - 0s 2ms/step - loss: 12.8226
Epoch 792/2000
1/1 [=======

1/1 [==============================] - 0s 2ms/step - loss: 12.5245
Epoch 880/2000
1/1 [==============================] - 0s 2ms/step - loss: 12.5211
Epoch 881/2000
1/1 [==============================] - 0s 2ms/step - loss: 12.5178
Epoch 882/2000
1/1 [==============================] - 0s 2ms/step - loss: 12.5145
Epoch 883/2000
1/1 [==============================] - 0s 4ms/step - loss: 12.5112
Epoch 884/2000
1/1 [==============================] - 0s 996us/step - loss: 12.5079
Epoch 885/2000
1/1 [==============================] - 0s 998us/step - loss: 12.5046
Epoch 886/2000
1/1 [==============================] - 0s 3ms/step - loss: 12.5013
Epoch 887/2000
1/1 [==============================] - 0s 2ms/step - loss: 12.4980
Epoch 888/2000
1/1 [==============================] - 0s 3ms/step - loss: 12.4947
Epoch 889/2000
1/1 [==============================] - 0s 2ms/step - loss: 12.4914
Epoch 890/2000
1/1 [==============================] - 0s 2ms/step - loss: 12.4882
Epoch 891/2000
1/1 [=======

1/1 [==============================] - 0s 3ms/step - loss: 12.2052
Epoch 979/2000
1/1 [==============================] - 0s 998us/step - loss: 12.2020
Epoch 980/2000
1/1 [==============================] - 0s 2ms/step - loss: 12.1989
Epoch 981/2000
1/1 [==============================] - 0s 2ms/step - loss: 12.1957
Epoch 982/2000
1/1 [==============================] - 0s 2ms/step - loss: 12.1926
Epoch 983/2000
1/1 [==============================] - 0s 998us/step - loss: 12.1895
Epoch 984/2000
1/1 [==============================] - 0s 3ms/step - loss: 12.1863
Epoch 985/2000
1/1 [==============================] - 0s 3ms/step - loss: 12.1832
Epoch 986/2000
1/1 [==============================] - 0s 999us/step - loss: 12.1801
Epoch 987/2000
1/1 [==============================] - 0s 2ms/step - loss: 12.1770
Epoch 988/2000
1/1 [==============================] - 0s 2ms/step - loss: 12.1738
Epoch 989/2000
1/1 [==============================] - 0s 997us/step - loss: 12.1707
Epoch 990/2000
1/1 [===

1/1 [==============================] - 0s 2ms/step - loss: 11.9050
Epoch 1077/2000
1/1 [==============================] - 0s 3ms/step - loss: 11.9020
Epoch 1078/2000
1/1 [==============================] - 0s 2ms/step - loss: 11.8991
Epoch 1079/2000
1/1 [==============================] - 0s 2ms/step - loss: 11.8961
Epoch 1080/2000
1/1 [==============================] - 0s 2ms/step - loss: 11.8931
Epoch 1081/2000
1/1 [==============================] - 0s 2ms/step - loss: 11.8901
Epoch 1082/2000
1/1 [==============================] - 0s 2ms/step - loss: 11.8872
Epoch 1083/2000
1/1 [==============================] - 0s 2ms/step - loss: 11.8842
Epoch 1084/2000
1/1 [==============================] - 0s 4ms/step - loss: 11.8812
Epoch 1085/2000
1/1 [==============================] - 0s 3ms/step - loss: 11.8783
Epoch 1086/2000
1/1 [==============================] - 0s 2ms/step - loss: 11.8753
Epoch 1087/2000
1/1 [==============================] - 0s 998us/step - loss: 11.8723
Epoch 1088/2000
1/

1/1 [==============================] - 0s 998us/step - loss: 11.6200
Epoch 1175/2000
1/1 [==============================] - 0s 2ms/step - loss: 11.6171
Epoch 1176/2000
1/1 [==============================] - 0s 2ms/step - loss: 11.6143
Epoch 1177/2000
1/1 [==============================] - 0s 997us/step - loss: 11.6115
Epoch 1178/2000
1/1 [==============================] - 0s 2ms/step - loss: 11.6086
Epoch 1179/2000
1/1 [==============================] - 0s 2ms/step - loss: 11.6058
Epoch 1180/2000
1/1 [==============================] - 0s 998us/step - loss: 11.6030
Epoch 1181/2000
1/1 [==============================] - 0s 997us/step - loss: 11.6002
Epoch 1182/2000
1/1 [==============================] - 0s 3ms/step - loss: 11.5973
Epoch 1183/2000
1/1 [==============================] - 0s 2ms/step - loss: 11.5945
Epoch 1184/2000
1/1 [==============================] - 0s 2ms/step - loss: 11.5917
Epoch 1185/2000
1/1 [==============================] - 0s 2ms/step - loss: 11.5889
Epoch 1186/2

1/1 [==============================] - 0s 997us/step - loss: 11.3492
Epoch 1273/2000
1/1 [==============================] - 0s 2ms/step - loss: 11.3465
Epoch 1274/2000
1/1 [==============================] - 0s 3ms/step - loss: 11.3438
Epoch 1275/2000
1/1 [==============================] - 0s 2ms/step - loss: 11.3411
Epoch 1276/2000
1/1 [==============================] - 0s 2ms/step - loss: 11.3384
Epoch 1277/2000
1/1 [==============================] - 0s 2ms/step - loss: 11.3357
Epoch 1278/2000
1/1 [==============================] - 0s 2ms/step - loss: 11.3330
Epoch 1279/2000
1/1 [==============================] - 0s 2ms/step - loss: 11.3304
Epoch 1280/2000
1/1 [==============================] - 0s 4ms/step - loss: 11.3277
Epoch 1281/2000
1/1 [==============================] - 0s 2ms/step - loss: 11.3250
Epoch 1282/2000
1/1 [==============================] - 0s 997us/step - loss: 11.3223
Epoch 1283/2000
1/1 [==============================] - 0s 2ms/step - loss: 11.3196
Epoch 1284/2000


1/1 [==============================] - 0s 2ms/step - loss: 11.0919
Epoch 1371/2000
1/1 [==============================] - 0s 997us/step - loss: 11.0893
Epoch 1372/2000
1/1 [==============================] - 0s 998us/step - loss: 11.0868
Epoch 1373/2000
1/1 [==============================] - 0s 2ms/step - loss: 11.0842
Epoch 1374/2000
1/1 [==============================] - 0s 2ms/step - loss: 11.0817
Epoch 1375/2000
1/1 [==============================] - 0s 2ms/step - loss: 11.0791
Epoch 1376/2000
1/1 [==============================] - 0s 5ms/step - loss: 11.0766
Epoch 1377/2000
1/1 [==============================] - 0s 2ms/step - loss: 11.0740
Epoch 1378/2000
1/1 [==============================] - 0s 3ms/step - loss: 11.0715
Epoch 1379/2000
1/1 [==============================] - 0s 2ms/step - loss: 11.0689
Epoch 1380/2000
1/1 [==============================] - 0s 2ms/step - loss: 11.0664
Epoch 1381/2000
1/1 [==============================] - 0s 2ms/step - loss: 11.0638
Epoch 1382/2000


1/1 [==============================] - 0s 997us/step - loss: 10.8474
Epoch 1469/2000
1/1 [==============================] - 0s 2ms/step - loss: 10.8450
Epoch 1470/2000
1/1 [==============================] - 0s 3ms/step - loss: 10.8426
Epoch 1471/2000
1/1 [==============================] - 0s 4ms/step - loss: 10.8402
Epoch 1472/2000
1/1 [==============================] - 0s 998us/step - loss: 10.8377
Epoch 1473/2000
1/1 [==============================] - 0s 4ms/step - loss: 10.8353
Epoch 1474/2000
1/1 [==============================] - 0s 1ms/step - loss: 10.8329
Epoch 1475/2000
1/1 [==============================] - 0s 2ms/step - loss: 10.8305
Epoch 1476/2000
1/1 [==============================] - 0s 2ms/step - loss: 10.8280
Epoch 1477/2000
1/1 [==============================] - 0s 998us/step - loss: 10.8256
Epoch 1478/2000
1/1 [==============================] - 0s 2ms/step - loss: 10.8232
Epoch 1479/2000
1/1 [==============================] - 0s 2ms/step - loss: 10.8208
Epoch 1480/200

1/1 [==============================] - 0s 4ms/step - loss: 10.6152
Epoch 1567/2000
1/1 [==============================] - 0s 3ms/step - loss: 10.6129
Epoch 1568/2000
1/1 [==============================] - 0s 2ms/step - loss: 10.6106
Epoch 1569/2000
1/1 [==============================] - 0s 998us/step - loss: 10.6083
Epoch 1570/2000
1/1 [==============================] - 0s 2ms/step - loss: 10.6060
Epoch 1571/2000
1/1 [==============================] - 0s 6ms/step - loss: 10.6036
Epoch 1572/2000
1/1 [==============================] - 0s 2ms/step - loss: 10.6013
Epoch 1573/2000
1/1 [==============================] - 0s 2ms/step - loss: 10.5990
Epoch 1574/2000
1/1 [==============================] - 0s 997us/step - loss: 10.5967
Epoch 1575/2000
1/1 [==============================] - 0s 1000us/step - loss: 10.5944
Epoch 1576/2000
1/1 [==============================] - 0s 998us/step - loss: 10.5921
Epoch 1577/2000
1/1 [==============================] - 0s 996us/step - loss: 10.5898
Epoch 157

1/1 [==============================] - 0s 2ms/step - loss: 10.3945
Epoch 1665/2000
1/1 [==============================] - 0s 2ms/step - loss: 10.3923
Epoch 1666/2000
1/1 [==============================] - 0s 4ms/step - loss: 10.3901
Epoch 1667/2000
1/1 [==============================] - 0s 2ms/step - loss: 10.3879
Epoch 1668/2000
1/1 [==============================] - 0s 998us/step - loss: 10.3857
Epoch 1669/2000
1/1 [==============================] - 0s 3ms/step - loss: 10.3835
Epoch 1670/2000
1/1 [==============================] - 0s 996us/step - loss: 10.3813
Epoch 1671/2000
1/1 [==============================] - 0s 2ms/step - loss: 10.3791
Epoch 1672/2000
1/1 [==============================] - 0s 2ms/step - loss: 10.3769
Epoch 1673/2000
1/1 [==============================] - 0s 998us/step - loss: 10.3748
Epoch 1674/2000
1/1 [==============================] - 0s 2ms/step - loss: 10.3726
Epoch 1675/2000
1/1 [==============================] - 0s 998us/step - loss: 10.3704
Epoch 1676/2

1/1 [==============================] - 0s 2ms/step - loss: 10.1848
Epoch 1763/2000
1/1 [==============================] - 0s 2ms/step - loss: 10.1827
Epoch 1764/2000
1/1 [==============================] - 0s 3ms/step - loss: 10.1806
Epoch 1765/2000
1/1 [==============================] - 0s 999us/step - loss: 10.1785
Epoch 1766/2000
1/1 [==============================] - 0s 2ms/step - loss: 10.1764
Epoch 1767/2000
1/1 [==============================] - 0s 10ms/step - loss: 10.1743
Epoch 1768/2000
1/1 [==============================] - 0s 2ms/step - loss: 10.1723
Epoch 1769/2000
1/1 [==============================] - 0s 2ms/step - loss: 10.1702
Epoch 1770/2000
1/1 [==============================] - 0s 997us/step - loss: 10.1681
Epoch 1771/2000
1/1 [==============================] - 0s 4ms/step - loss: 10.1660
Epoch 1772/2000
1/1 [==============================] - 0s 2ms/step - loss: 10.1639
Epoch 1773/2000
1/1 [==============================] - 0s 999us/step - loss: 10.1619
Epoch 1774/20

1/1 [==============================] - 0s 2ms/step - loss: 9.9854
Epoch 1861/2000
1/1 [==============================] - 0s 2ms/step - loss: 9.9834
Epoch 1862/2000
1/1 [==============================] - 0s 2ms/step - loss: 9.9815
Epoch 1863/2000
1/1 [==============================] - 0s 2ms/step - loss: 9.9795
Epoch 1864/2000
1/1 [==============================] - 0s 997us/step - loss: 9.9775
Epoch 1865/2000
1/1 [==============================] - 0s 2ms/step - loss: 9.9755
Epoch 1866/2000
1/1 [==============================] - 0s 993us/step - loss: 9.9735
Epoch 1867/2000
1/1 [==============================] - 0s 2ms/step - loss: 9.9716
Epoch 1868/2000
1/1 [==============================] - 0s 997us/step - loss: 9.9696
Epoch 1869/2000
1/1 [==============================] - 0s 2ms/step - loss: 9.9676
Epoch 1870/2000
1/1 [==============================] - 0s 2ms/step - loss: 9.9657
Epoch 1871/2000
1/1 [==============================] - 0s 2ms/step - loss: 9.9637
Epoch 1872/2000
1/1 [=====

1/1 [==============================] - 0s 2ms/step - loss: 9.7941
Epoch 1960/2000
1/1 [==============================] - 0s 2ms/step - loss: 9.7922
Epoch 1961/2000
1/1 [==============================] - 0s 2ms/step - loss: 9.7903
Epoch 1962/2000
1/1 [==============================] - 0s 2ms/step - loss: 9.7884
Epoch 1963/2000
1/1 [==============================] - 0s 2ms/step - loss: 9.7866
Epoch 1964/2000
1/1 [==============================] - 0s 997us/step - loss: 9.7847
Epoch 1965/2000
1/1 [==============================] - 0s 997us/step - loss: 9.7828
Epoch 1966/2000
1/1 [==============================] - 0s 2ms/step - loss: 9.7809
Epoch 1967/2000
1/1 [==============================] - 0s 2ms/step - loss: 9.7790
Epoch 1968/2000
1/1 [==============================] - 0s 2ms/step - loss: 9.7772
Epoch 1969/2000
1/1 [==============================] - 0s 3ms/step - loss: 9.7753
Epoch 1970/2000
1/1 [==============================] - 0s 2ms/step - loss: 9.7734
Epoch 1971/2000
1/1 [=======